pull_request_rules:
  - name: comment as victim with a command
    conditions:
      - label=go-cmd
    actions:
      comment:
        message: "@mergifyio rebase"
        bot_account: "Pockriglian"
